service: vacunacovid-telegrambot

plugins:
  - serverless-python-requirements
  - serverless-plugin-aws-alerts

custom:
  pythonRequirements:
    dockerizePip: non-linux
  alerts:
    stages:
      - pro
    topics:
      alarm:
        topic: ${self:service}-${opt:stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${env:NOTIFICATIONS_EMAIL}
    alarms:
      - functionErrors
    definitions:
      functionErrors:
        treatMissingData: notBreaching

  table:
    dev: "vaccine-notifications-dev"
    pro: "vaccine-notifications-pro"
  throughput:
    dev: 1
    pro: 5


provider:
  name: aws
  runtime: python3.7
  stage: dev
  timeout: 15
  region: eu-west-1
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - ssm:PutParameter
        - ssm:GetParameter
      Resource:
        - "*"
  environment:
    NOTIFICATIONS_TABLE: ${self:custom.table.${opt:stage, self:provider.stage}}
    BOT_TOKEN: ${env:BOT_TOKEN}

functions:
  message_handler:
    handler: main.handle_telegram_message
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
  checker:
    handler: main.handle_check
    timeout: 900
    events:
      - schedule: rate(20 minutes)

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.${opt:stage, self:provider.stage}}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.throughput.${opt:stage, self:provider.stage}}
          WriteCapacityUnits: ${self:custom.throughput.${opt:stage, self:provider.stage}}
