service: vacunacovid-telegrambot

plugins:
  - serverless-python-requirements
  - serverless-plugin-aws-alerts

custom:
  pythonRequirements:
    dockerizePip: non-linux
  alerts:
    stages:
      - pro
    topics:
      alarm:
        topic: ${self:service}-${opt:stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${env:NOTIFICATIONS_EMAIL}
    alarms:
      - functionErrors
    definitions:
      functionErrors:
        treatMissingData: notBreaching

provider:
  name: aws
  runtime: python3.7
  stage: dev
  timeout: 15
  region: eu-west-1
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - ssm:GetParameter
      Resource:
        - "*"
  environment:
    BOT_TOKEN: ${env:BOT_TOKEN}
    PARAM_MIN_YEARS: ${self:custom.min_years_param.${opt:stage, self:provider.stage}}
    STAGE: ${opt:stage}
    THIRD_DOSE_INFO_PARAMETER: "/autocita/madrid/third-dose-info"

functions:
  message_handler:
    handler: main.handle_telegram_message
    timeout: 30
    url: true
