name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download Node
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Install serverless dependencies
      run: npm install -g serverless-python-requirements
    - name: Serverless Authentication
      run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
    - name: Deploy to AWS [DEV]
      if: github.ref == 'refs/heads/develop'
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN_DEV }}
      run: serverless deploy -v -s pro
    - name: Deploy to AWS [PRO]
      if: github.ref == 'refs/heads/main'
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN_PRO }}
      run: serverless deploy -v -s pro
